nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

image:
  repository: foreman-release-operator
  tag: development
  pullPolicy: IfNotPresent

controller:
  replicas: 2
  pollSeconds: 5
  commandTimeoutSeconds: 60
  commandTerminationGraceSeconds: 5
  releaseLeaseDurationSeconds: 300
  leaderLeaseName: foreman-release-controller-leader
  leaderLeaseDurationSeconds: 30
  terminationGracePeriodSeconds: 30

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  clusterPreflight: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 512Mi
