{{- if not .Values.foreman.sharedTmp.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foreman-stack.fullname" . }}-foreman-tmp
  labels:
    {{- include "foreman-stack.componentLabels" (dict "root" . "component" "foreman-tmp") | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.foreman.sharedTmp.accessMode }}
  {{- with .Values.foreman.sharedTmp.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.foreman.sharedTmp.size }}
{{- end }}
